### ISSUE TITLE
처우만큼 중요한게 같이 일하는 동료라고 생각이 들어서 드는 생각인데,

### ISSUE THREAD

**Issue by deepkyu** [mindslab-ai/mindslab-ai.github.io#30]
처우만큼 중요한게 같이 일하는 동료라고 생각이 들어서 드는 생각인데,
`Career`에서 말고 People에서 재직자/퇴직자를 간단하게 list up 하는 것은 어떨까요?

_Originally posted by @sunggukcha in https://github.com/mindslab-ai/mindslab-ai.github.io/pull/29#issuecomment-1144478087_

**Comment by tonyswoo** [comment]
현재 팀원들 리스팅하는 건 별개로 퇴직자 리스팅은 별로 좋은 생각이 아닐 것 같습니다...

**Comment by seungwonpark** [comment]
안녕하세요 깃헙 구경하다가 놀러온 퇴직자입니다 (?)

대학 연구실에서 Alumni 리스팅하는것처럼 former member도 띄우면 어떨까 하는 생각을 2년 전에 재직 중일 때에도 했었는데, 모두의 동의를 얻기는 어려울 것 같아서 실행하지 않았던 기획이었습니다.
대신 Publications / Open-source 리스트에는 이전에 일하셨던 분들 성함이 같이 나와있으니, 그 정도로도 충분하지 않을까 싶네요. (그런 활동이 없으셨던 분들은 성함을 넣지 못해 아쉽긴 하지만...)

블로그 잘 보고 갑니다. 되게 예쁘게 단장이 됐네요 ㅎㅎ

**Comment by deepkyu** [comment]
@seungwonpark 
승원님 오랜만이네요 ㅎㅎ comments 달아주셔서 감사합니다 🙇🏻 

@sunggukcha 
저도 현실적으로 퇴직자 listing에 대해 퇴직자 개개인에 동의를 구해야 한다는 부분에서 어려움이 있을 것 같습니다 ㅠㅠ
다만, 조금 별개의 이야기일 수는 있겠지만 Alumni 커뮤니티가 있으면 참 좋겠다는 생각은 드네요..
(나간다고 이러는거 아님)
