### ISSUE TITLE
포스트 제목 부분 디자인 제안(category, github profile)

### ISSUE THREAD

**Issue by CoaLee** [mindslab-ai/mindslab-ai.github.io#7]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/27776717/126275240-79cecef1-0dc5-4f51-8805-914d5d59001d.png">

### 제안 
1. 제목 앞에 category box(button?)가 있으면 좋겠다.
2. 포스트 목록에서는 github profile이 나오는데, 포스트에서는 안나오고 있어서 포스트에도 있으면 좋겠다.

어떻게 생각하시나요?

**Comment by deepkyu** [comment]
Docusaurus로 변경한만큼 issue close 하겠습니다.
